stages:
  - build

image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: abkrim/laravel-gitlab-ci
  IMAGE_TAG: "8.3"

before_script:
  - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

build-and-push-8_3:
  stage: build
  script:
    # 1) Build single-arch (runner arch) for quick validation with goss
    - docker build -t $IMAGE_NAME:ci-$CI_COMMIT_SHORT_SHA -f php/8.3/Dockerfile .
    - docker run --rm -v $(pwd):/var/www/html $IMAGE_NAME:ci-$CI_COMMIT_SHORT_SHA goss -g tests/goss-8.3.yaml v

    # 2) Enable multi-arch and push manifest for amd64+arm64
    - docker run --privileged --rm tonistiigi/binfmt --install arm64,amd64
    - docker buildx create --name multi --use || docker buildx use multi
    - docker buildx inspect --bootstrap
    - docker buildx build \
        --platform linux/amd64,linux/arm64 \
        --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA \
        --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
        -t $IMAGE_NAME:$IMAGE_TAG \
        -t $IMAGE_NAME:latest \
        -f php/8.3/Dockerfile \
        . \
        --push

  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success

## Upstream legacy jobs removed: this fork only builds PHP 8.3 image

##

##

##

##

##

##

##


##

##


##


Chromium 8.0:
  stage: build-chromium
  variables:
    IMAGE_VERSION: "8.0-chromium"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/8.0/chromium/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss -g tests/goss-8.0.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always
  dependencies:
    - Debian 8.0

Chromium 7.4:
  stage: build-chromium
  variables:
    IMAGE_VERSION: "7.4-chromium"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.4/chromium/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss -g tests/goss-7.4.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always
  dependencies:
    - Debian 7.4

Chromium 7.3:
  stage: build-chromium
  variables:
    IMAGE_VERSION: "7.3-chromium"
  script:
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.3/chromium/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss -g tests/goss-7.3.yaml v
    - docker push $NAMESPACE:$IMAGE_VERSION
  when: always
  dependencies:
    - Debian 7.3
