name: Build and Push Docker Images

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: abkrim/laravel-gitlab-ci

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [default, alpine, fpm, chromium]
        include:
          - variant: default
            dockerfile: php/8.3/Dockerfile
            tag: 8.3
          - variant: alpine
            dockerfile: php/8.3/alpine/Dockerfile
            tag: 8.3-alpine
          - variant: fpm
            dockerfile: php/8.3/fpm/Dockerfile
            tag: 8.3-fpm
          - variant: chromium
            dockerfile: php/8.3/chromium/Dockerfile
            tag: 8.3-chromium

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=${{ matrix.tag }},enable={{is_default_branch}}
          type=raw,value=latest,enable={{is_default_branch && matrix.variant == 'default'}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max